using System.Collections.Generic;
using System.Text;

namespace RetroSk8.Core
{
    /// <summary>
    /// Phase 18: the exact Game Center setup App Store Connect needs, generated from the same lists the game uses,
    /// so a leaderboard or achievement id can never drift from the code. Written to GameCenterSetup.md by
    /// Retro Sk8 → Build iOS → Write Game Center Setup List (bridge: <c>gamecenter</c>).
    /// </summary>
    public static class GameCenterSetup
    {
        /// <summary>Game Center allows at most 1,000 achievement points per app.</summary>
        public const int MaxPoints = 1000;

        /// <summary>Points per achievement (harder ones are worth more). Total stays under <see cref="MaxPoints"/>.</summary>
        public static int PointsFor(string achievementId)
        {
            switch (achievementId)
            {
                case "class_dismissed": return 10;
                case "first_bank": return 10;
                case "line_10k": return 25;
                case "line_50k": return 75;
                case "run_100k": return 75;
                case "spin_540": return 25;
                case "gap_hunter": return 50;
                case "contractor": return 25;
                case "all_contracts": return 100;
                case "daily_regular": return 50;
                case "tourist": return 50;
                case "double_feature": return 75;
                case "rink_rats": return 75;
                case "dry_dock": return 75;
                case "daily_driver": return 50;
                case "called_it": return 25;
                case "bonk_collector": return 50;
                case "mind_the_gap": return 25;
                default: return 25;
            }
        }

        public static int TotalPoints(IEnumerable<AchievementDefinition> achievements)
        {
            int total = 0;
            if (achievements != null) foreach (var a in achievements) total += PointsFor(a.Id);
            return total;
        }

        /// <summary>"Low to High" for time boards, "High to Low" for everything else.</summary>
        public static string SortOrder(BoardInfo b) => b.LowerIsBetter ? "Low to High" : "High to Low";

        /// <summary>The App Store Connect score format for a board.</summary>
        public static string ScoreFormat(BoardInfo b) =>
            b.Format == BoardFormat.Time ? "Elapsed Time (hundredths of a second)" : "Integer";

        /// <summary>Recurring boards (the weekly event resets every Monday).</summary>
        public static bool IsRecurring(BoardInfo b) => b.Id == WeeklyEvents.LeaderboardId;

        /// <summary>Reference names in App Store Connect are private but must be unique: "Retro Sk8 – PARKS – HARBOR PLAZA".</summary>
        public static string ReferenceName(BoardInfo b) => "RS8 " + LeaderboardHub.GroupName(b.Group) + " - " + b.Title;

        public static string Markdown(IList<BoardInfo> boards, IEnumerable<AchievementDefinition> achievements)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# Retro Sk8 — Game Center setup (generated)");
            sb.AppendLine();
            sb.AppendLine("Generated by **Retro Sk8 → Build iOS → Write Game Center Setup List** from the game's own lists. Create each item in App Store Connect → your app → **Game Center**, with the ID copied exactly. Regenerate after adding parks, races or achievements.");
            sb.AppendLine();
            sb.AppendLine($"## Leaderboards ({boards?.Count ?? 0})");
            sb.AppendLine();
            sb.AppendLine("Type **Classic**. Score submission: **Best Score**. Display name in English (U.S.) = the title.");
            sb.AppendLine();
            sb.AppendLine("**Score range** (Phase 19 anti-cheat): set it on every leaderboard. Game Center then ignores scores outside it, even from a modified copy of the game.");
            sb.AppendLine();
            sb.AppendLine("| ID | Title | Format | Sort | Score range | Notes |");
            sb.AppendLine("|---|---|---|---|---|---|");
            if (boards != null)
                foreach (var b in boards)
                {
                    string notes = IsRecurring(b) ? "**Recurring**: weekly, starts on a Monday 00:00" : (b.Format == BoardFormat.Time ? "Race time" : "");
                    var (min, max) = ScoreLimits.RangeFor(b.Id);
                    sb.AppendLine($"| `{b.Id}` | {b.Title} | {ScoreFormat(b)} | {SortOrder(b)} | {min} – {max} | {notes} |");
                }
            sb.AppendLine();
            var list = new List<AchievementDefinition>();
            if (achievements != null) list.AddRange(achievements);
            sb.AppendLine($"## Achievements ({list.Count}, {TotalPoints(list)} of {MaxPoints} points)");
            sb.AppendLine();
            sb.AppendLine("Each needs an image: use `AppStoreAssets/Achievements/<name>.png` (1024 × 1024, made by `Tools/make_badges.py`). Hidden: **No**. Achievable more than once: **No**.");
            sb.AppendLine();
            sb.AppendLine("| ID | Title | Points | Pre-earned description | Earned description | Image |");
            sb.AppendLine("|---|---|---|---|---|---|");
            foreach (var a in list)
                sb.AppendLine($"| `{Achievements.GameCenterId(a)}` | {a.Title} | {PointsFor(a.Id)} | {a.Description} | {Earned(a.Description)} | `{a.Id}.png` |");
            return sb.ToString();
        }

        /// <summary>"Land a 540." → "You landed a 540." style past-tense text for the earned description.</summary>
        public static string Earned(string description)
        {
            if (string.IsNullOrEmpty(description)) return "Done!";
            return "Done: " + char.ToLowerInvariant(description[0]) + description.Substring(1);
        }
    }
}
